# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fc7facf6-3bf1-4d6a-b85f-ba2def9b1b79";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/98C0-72EB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/nixpool" =
    { device = "nixpool";
      fsType = "zfs";
    };

  fileSystems."/mnt/nixpool/immich" =
    { device = "nixpool/immich";
      fsType = "zfs";
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/92291989-678d-4ac5-8a73-f1ac95721c05";
      fsType = "ext4";
    };

  fileSystems."/var/lib/containers/storage/overlay" =
    { device = "/var/lib/containers/storage/overlay";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/831f834f-905f-4c84-ba88-d2e7bbadcf95"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
